const baseUrl = "https://raw.githubusercontent.com/Juenfy/resources/refs/heads/master/emoji/"
const emoji = {
    kaixinmao: [{
        name: 'kaixinmao_1',
        ext: 'gif',
        default: true
    }, {
        name: 'kaixinmao_2',
        ext: 'gif',
        default: true
    }, {
        name: 'kaixinmao_3',
        ext: 'gif',
        default: true
    }, {
        name: 'kaixinmao_4',
        ext: 'gif',
        default: true
    }, {
        name: 'kaixinmao_5',
        ext: 'gif',
        default: true
    }, {
        name: 'kaixinmao_6',
        ext: 'gif',
        default: true
    },],
    qiuqiu: [{
        name: 'qiuqiu_1',
        ext: 'gif',
        default: true
    }, {
        name: 'qiuqiu_2',
        ext: 'gif',
        default: true
    }, {
        name: 'qiuqiu_3',
        ext: 'gif',
        default: true
    }, {
        name: 'qiuqiu_4',
        ext: 'gif',
        default: true
    }, {
        name: 'qiuqiu_5',
        ext: 'gif',
        default: true
    }, {
        name: 'qiuqiu_6',
        ext: 'gif',
        default: true
    }, {
        name: 'qiuqiu_7',
        ext: 'gif',
        default: true
    }, {
        name: 'qiuqiu_8',
        ext: 'gif',
        default: true
    },],
    Silvervale: [{
        name: 'Silvervale_1',
        ext: 'jpg',
        default: true
    }, {
        name: 'Silvervale_2',
        ext: 'gif',
        default: true
    }, {
        name: 'Silvervale_3',
        ext: 'gif',
        default: true
    }, {
        name: 'Silvervale_4',
        ext: 'gif',
        default: true
    }, {
        name: 'Silvervale_5',
        ext: 'jpg',
        default: true
    }, {
        name: 'Silvervale_6',
        ext: 'gif',
        default: true
    }, {
        name: 'Silvervale_7',
        ext: 'gif',
        default: true
    }, {
        name: 'Silvervale_8',
        ext: 'gif',
        default: true
    }, {
        name: 'Silvervale_9',
        ext: 'jpg',
        default: true
    }, {
        name: 'Silvervale_10',
        ext: 'gif',
        default: true
    }, {
        name: 'Silvervale_11',
        ext: 'gif',
        default: true
    }, {
        name: 'Silvervale_12',
        ext: 'gif',
        default: true
    }, {
        name: 'Silvervale_13',
        ext: 'gif',
        default: true
    }, {
        name: 'Silvervale_14',
        ext: 'jpg',
        default: true
    }, {
        name: 'Silvervale_15',
        ext: 'gif',
        default: true
    }, {
        name: 'Silvervale_16',
        ext: 'gif',
        default: true
    }, {
        name: 'Silvervale_17',
        ext: 'jpg',
        default: true
    }, {
        name: 'Silvervale_18',
        ext: 'gif',
        default: true
    }, {
        name: 'Silvervale_19',
        ext: 'gif',
        default: true
    }, {
        name: 'Silvervale_20',
        ext: 'gif',
        default: true
    }, {
        name: 'Silvervale_21',
        ext: 'gif',
        default: true
    }, {
        name: 'Silvervale_22',
        ext: 'jpg',
        default: true
    }, {
        name: 'Silvervale_23',
        ext: 'gif',
        default: true
    }, {
        name: 'Silvervale_24',
        ext: 'gif',
        default: true
    }, {
        name: 'Silvervale_25',
        ext: 'gif',
        default: true
    }, {
        name: 'Silvervale_26',
        ext: 'gif',
        default: true
    }, {
        name: 'Silvervale_27',
        ext: 'gif',
        default: true
    }, {
        name: 'Silvervale_28',
        ext: 'gif',
        default: true
    }, {
        name: 'Silvervale_29',
        ext: 'jpg',
        default: true
    }, {
        name: 'Silvervale_30',
        ext: 'gif',
        default: true
    }, {
        name: 'Silvervale_31',
        ext: 'gif',
        default: true
    }, {
        name: 'Silvervale_32',
        ext: 'gif',
        default: true
    }, {
        name: 'Silvervale_33',
        ext: 'jpg',
        default: true
    }, {
        name: 'Silvervale_34',
        ext: 'jpg',
        default: true
    }, {
        name: 'Silvervale_35',
        ext: 'jpg',
        default: true
    }, {
        name: 'Silvervale_36',
        ext: 'jpg',
        default: true
    }, {
        name: 'Silvervale_37',
        ext: 'gif',
        default: true
    }, {
        name: 'Silvervale_38',
        ext: 'gif',
        default: true
    }, {
        name: 'Silvervale_39',
        ext: 'gif',
        default: true
    }, {
        name: 'Silvervale_40',
        ext: 'gif',
        default: true
    }, {
        name: 'Silvervale_41',
        ext: 'gif',
        default: true
    }, {
        name: 'Silvervale_42',
        ext: 'gif',
        default: true
    }, {
        name: 'Silvervale_43',
        ext: 'gif',
        default: true
    }, {
        name: 'Silvervale_44',
        ext: 'gif',
        default: true
    }, {
        name: 'Silvervale_45',
        ext: 'jpg',
        default: true
    }, {
        name: 'Silvervale_46',
        ext: 'jpg',
        default: true
    }, {
        name: 'Silvervale_47',
        ext: 'jpg',
        default: true
    }, {
        name: 'Silvervale_48',
        ext: 'gif',
        default: true
    }, {
        name: 'Silvervale_49',
        ext: 'jpg',
        default: true
    }, {
        name: 'Silvervale_50',
        ext: 'gif',
        default: true
    }, {
        name: 'Silvervale_51',
        ext: 'gif',
        default: true
    }, {
        name: 'Silvervale_52',
        ext: 'gif',
        default: true
    }, {
        name: 'Silvervale_53',
        ext: 'jpg',
        default: true
    }, {
        name: 'Silvervale_54',
        ext: 'gif',
        default: true
    }, {
        name: 'Silvervale_55',
        ext: 'gif',
        default: true
    }, {
        name: 'Silvervale_56',
        ext: 'gif',
        default: true
    }, {
        name: 'Silvervale_57',
        ext: 'gif',
        default: true
    }, {
        name: 'Silvervale_58',
        ext: 'gif',
        default: true
    }, {
        name: 'Silvervale_59',
        ext: 'gif',
        default: true
    }, {
        name: 'Silvervale_60',
        ext: 'gif',
        default: true
    }, {
        name: 'Silvervale_61',
        ext: 'jpg',
        default: true
    }, {
        name: 'Silvervale_62',
        ext: 'gif',
        default: true
    }, {
        name: 'Silvervale_63',
        ext: 'jpg',
        default: true
    }, {
        name: 'Silvervale_64',
        ext: 'jpg',
        default: true
    }, {
        name: 'Silvervale_65',
        ext: 'gif',
        default: true
    }, {
        name: 'Silvervale_66',
        ext: 'gif',
        default: true
    }, {
        name: 'Silvervale_67',
        ext: 'jpg',
        default: true
    }, {
        name: 'Silvervale_68',
        ext: 'jpg',
        default: true
    }, {
        name: 'Silvervale_69',
        ext: 'jpg',
        default: true
    }, {
        name: 'Silvervale_70',
        ext: 'jpg',
        default: true
    }, {
        name: 'Silvervale_71',
        ext: 'gif',
        default: true
    }, {
        name: 'Silvervale_72',
        ext: 'gif',
        default: true
    },],
    znbqb: [{
        name: 'znbqb_1',
        ext: 'jpeg',
        default: true
    }, {
        name: 'znbqb_2',
        ext: 'png',
        default: true
    }, {
        name: 'znbqb_3',
        ext: 'png',
        default: true
    }, {
        name: 'znbqb_4',
        ext: 'png',
        default: true
    }, {
        name: 'znbqb_5',
        ext: 'png',
        default: true
    }, {
        name: 'znbqb_6',
        ext: 'jpeg',
        default: true
    }, {
        name: 'znbqb_7',
        ext: 'jpeg',
        default: true
    }, {
        name: 'znbqb_8',
        ext: 'jpeg',
        default: true
    }, {
        name: 'znbqb_9',
        ext: 'jpeg',
        default: true
    }, {
        name: 'znbqb_10',
        ext: 'jpeg',
        default: true
    }, {
        name: 'znbqb_11',
        ext: 'jpeg',
        default: true
    }, {
        name: 'znbqb_12',
        ext: 'jpeg',
        default: true
    }, {
        name: 'znbqb_13',
        ext: 'jpeg',
        default: true
    }, {
        name: 'znbqb_14',
        ext: 'png',
        default: true
    }, {
        name: 'znbqb_15',
        ext: 'png',
        default: true
    }, {
        name: 'znbqb_16',
        ext: 'png',
        default: true
    }, {
        name: 'znbqb_17',
        ext: 'png',
        default: true
    },],
    zongzimiao: [{
        name: 'zongzimiao_1',
        ext: 'gif',
        default: true
    }, {
        name: 'zongzimiao_2',
        ext: 'gif',
        default: true
    }, {
        name: 'zongzimiao_3',
        ext: 'gif',
        default: true
    }, {
        name: 'zongzimiao_4',
        ext: 'gif',
        default: true
    }, {
        name: 'zongzimiao_5',
        ext: 'gif',
        default: true
    }, {
        name: 'zongzimiao_6',
        ext: 'gif',
        default: true
    }, {
        name: 'zongzimiao_7',
        ext: 'gif',
        default: true
    }, {
        name: 'zongzimiao_8',
        ext: 'gif',
        default: true
    },],
}
export {emoji, baseUrl}